"""
BaseTeamAgent P5 升级 — 单元测试（Mock LLM，无需 API Key）。

运行:
    cd backend
    python -m applications.software_team.tests.test_base_team_agent
"""

from __future__ import annotations

from unittest.mock import MagicMock
from uuid import uuid4

from app.agents.types import AgentContext
from app.agents.types import AgentResult
from app.memory.manager import MemoryManager

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)
from applications.software_team.project.artifacts.artifact_manager import (
    ArtifactManager,
)
from applications.software_team.project.models.project import Project
from applications.software_team.project.models.project_status import ProjectStatus
from applications.software_team.project.workspace.workspace_manager import (
    WorkspaceManager,
)
from applications.software_team.runtime.team_agent_runtime import TeamAgentRuntime


class _StubAgent(BaseTeamAgent):
    """
    用于测试 BaseTeamAgent 智能循环的最小实现。
    """

    @property
    def agent_name(self) -> str:

        return "StubAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        return self._run_intelligent_loop(context)


def _build_test_agent(
    tmp_workspace: str,
) -> _StubAgent:

    project = Project(
        id="proj_test",
        name="test_project",
        requirement="开发一个测试系统",
        workspace_path=tmp_workspace,
        status=ProjectStatus.PLANNING,
    )

    artifact_manager = ArtifactManager()
    workspace_manager = WorkspaceManager(
        workspace_root=tmp_workspace,
    )

    mock_executor = MagicMock()
    mock_executor.run.return_value = AgentResult(
        success=True,
        model="mock",
        content="# Mock PRD\n\nGenerated by stub.",
    )

    runtime = TeamAgentRuntime(
        memory_manager=MemoryManager(),
        agent_executor=mock_executor,
    )

    return _StubAgent(
        project=project,
        artifact_manager=artifact_manager,
        workspace_manager=workspace_manager,
        team_agent_runtime=runtime,
    )


def test_intelligent_loop_builds_prompt_and_calls_executor() -> None:

    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as tmp:

        agent = _build_test_agent(tmp)

        context = CoordinatorContext(
            session_id=f"test_{uuid4().hex[:8]}",
            user_message="开发一个测试系统",
            project=agent.project,
            metadata={"current_task": "生成 PRD"},
            shared_context={"requirement": "开发一个测试系统"},
            agent_name="StubAgent",
        )

        agent_context = AgentContext(
            session_id=context.session_id,
            user_message=context.user_message,
            agent_name="StubAgent",
        )

        result = agent.run(agent_context)

        assert result.success is True
        assert "Mock PRD" in result.content

        mock_executor = agent.runtime.agent_executor
        mock_executor.run.assert_called_once()

        call_args = mock_executor.run.call_args
        messages = call_args[0][1]

        assert len(messages) > 0
        assert any(
            message.role == "system"
            for message in messages
        )


def test_team_memory_is_saved_after_success() -> None:

    import tempfile

    with tempfile.TemporaryDirectory() as tmp:

        agent = _build_test_agent(tmp)
        session_id = f"mem_{uuid4().hex[:8]}"

        context = CoordinatorContext(
            session_id=session_id,
            user_message="开发一个测试系统",
            project=agent.project,
            metadata={},
            shared_context={},
        )

        agent._run_intelligent_loop(context)

        memory_context = agent.memory.load(session_id)
        memory_records = [
            record
            for record in memory_context.records
            if record.metadata.get("type") == "memory"
        ]

        assert len(memory_records) >= 1
        assert memory_records[0].metadata.get("agent") == "StubAgent"


def main() -> None:

    test_intelligent_loop_builds_prompt_and_calls_executor()
    test_team_memory_is_saved_after_success()
    print("All BaseTeamAgent tests passed.")


if __name__ == "__main__":

    main()
