from __future__ import annotations

from datetime import datetime
from pathlib import Path

from applications.software_team.config.defaults import DEFAULT_ENCODING
from applications.software_team.config.settings import SoftwareTeamSettings
from applications.software_team.deployment.deployment_result import ReleaseResult
from applications.software_team.git.git_manager import GitManager
from applications.software_team.project.models.project import Project


class ReleaseManager:
    """
    版本发布：Release Notes、Version、Tag、Artifact Archive。
    """

    def __init__(
        self,
        settings: SoftwareTeamSettings | None = None,
        git_manager: GitManager | None = None,
    ):

        self._settings = settings or SoftwareTeamSettings()
        self._git = git_manager or GitManager(settings=self._settings)

    def release(
        self,
        workspace: str | Path,
        *,
        project: Project,
        archive_path: str = "",
        artifact_summary: str = "",
    ) -> ReleaseResult:

        workspace_path = Path(workspace).resolve()
        version = self._generate_version(project)
        tag = f"v{version}"

        notes_path = workspace_path / "RELEASE_NOTES.md"
        notes_content = self._build_release_notes(
            project=project,
            version=version,
            artifact_summary=artifact_summary,
        )

        notes_path.write_text(notes_content, encoding=DEFAULT_ENCODING)

        tag_result = None

        if (
            self._settings.enable_git
            and self._git.is_repo(workspace_path)
        ):

            tag_result = self._git.tag(
                workspace_path,
                tag,
                message=f"Release {project.name} {version}",
            )

        return ReleaseResult(
            success=True,
            workspace_path=str(workspace_path),
            version=version,
            tag=tag,
            release_notes_path=str(notes_path),
            archive_path=archive_path,
            metadata={
                "tag_success": (
                    tag_result.success
                    if tag_result is not None
                    else False
                ),
            },
        )

    def _generate_version(
        self,
        project: Project,
    ) -> str:

        if self._settings.deployment_version:

            return self._settings.deployment_version

        timestamp = datetime.utcnow().strftime("%Y.%m.%d")

        slug = project.name.lower().replace(" ", "-")[:10]

        return f"0.1.0-{slug}-{timestamp}"

    @staticmethod
    def _build_release_notes(
        *,
        project: Project,
        version: str,
        artifact_summary: str,
    ) -> str:

        return f"""# Release Notes — {project.name}

## Version
{version}

## Date
{datetime.utcnow().isoformat()}Z

## Summary
{project.description or project.requirement}

## Artifacts
{artifact_summary or "- See output/ deployment package"}

## Deployment
- Dockerfile
- docker-compose.yml
- deploy/deploy.sh

---
*Generated by ReleaseManager*
"""
