from __future__ import annotations

from pathlib import Path

from applications.software_team.config.defaults import DEFAULT_ENCODING
from applications.software_team.config.settings import SoftwareTeamSettings
from applications.software_team.management.management_result import PlanPhase
from applications.software_team.management.management_result import PlanningResult
from applications.software_team.management.management_result import ProjectPlan
from applications.software_team.project.models.project import Project
from applications.software_team.workflow.dependencies import DEFAULT_PIPELINE


class PlanningManager:
    """
    根据需求制定项目计划：阶段划分、时间规划、资源规划。
    """

    REPORT_DIR = "management"
    PLAN_NAME = "PROJECT_PLAN.md"

    _PHASE_DURATIONS: dict[str, int] = {
        "ProductAgent": 2,
        "ArchitectAgent": 3,
        "BackendAgent": 5,
        "FrontendAgent": 4,
        "QAAgent": 3,
        "DocumentationAgent": 2,
    }

    _PHASE_NAMES: dict[str, str] = {
        "ProductAgent": "Requirement Analysis",
        "ArchitectAgent": "System Design",
        "BackendAgent": "Backend Development",
        "FrontendAgent": "Frontend Development",
        "QAAgent": "Quality Assurance",
        "DocumentationAgent": "Documentation & Delivery",
    }

    def __init__(
        self,
        settings: SoftwareTeamSettings | None = None,
    ):

        self._settings = settings or SoftwareTeamSettings()

    def create_plan(
        self,
        project: Project,
    ) -> PlanningResult:

        phases: list[PlanPhase] = []

        for index, step in enumerate(DEFAULT_PIPELINE):

            duration = self._PHASE_DURATIONS.get(step.agent_name, 3)

            phases.append(
                PlanPhase(
                    name=self._PHASE_NAMES.get(
                        step.agent_name,
                        step.agent_name,
                    ),
                    agent_name=step.agent_name,
                    duration_days=duration,
                    description=step.task,
                    order=index,
                )
            )

        resources = sorted({phase.agent_name for phase in phases})

        plan = ProjectPlan(
            project_id=project.id,
            project_name=project.name,
            phases=phases,
            total_duration_days=sum(p.duration_days for p in phases),
            resources=resources,
            metadata={
                "requirement": project.requirement[:500],
                "tech_stack": project.tech_stack,
            },
        )

        plan_path = self._write_plan(project.workspace_path, plan, project)

        return PlanningResult(
            success=True,
            plan=plan,
            plan_path=str(plan_path),
        )

    def _write_plan(
        self,
        workspace: str | Path,
        plan: ProjectPlan,
        project: Project,
    ) -> Path:

        workspace_path = Path(workspace)
        report_dir = workspace_path / self.REPORT_DIR
        report_dir.mkdir(parents=True, exist_ok=True)

        report_path = report_dir / self.PLAN_NAME

        phase_lines = "\n".join(
            f"| {p.order + 1} | {p.name} | {p.agent_name} | "
            f"{p.duration_days}d | {p.description} |"
            for p in plan.phases
        )

        content = f"""# Project Plan — {project.name}

## Requirement
{project.requirement}

## Timeline
Total estimated duration: **{plan.total_duration_days} days**

## Phases
| # | Phase | Agent | Duration | Deliverable |
|---|-------|-------|----------|-------------|
{phase_lines}

## Resources
{', '.join(plan.resources)}

---
*Generated by PlanningManager*
"""

        report_path.write_text(content, encoding=DEFAULT_ENCODING)

        return report_path
