from __future__ import annotations

from pathlib import Path

from applications.software_team.config.defaults import DEFAULT_ENCODING
from applications.software_team.config.settings import SoftwareTeamSettings
from applications.software_team.management.management_result import ProgressSnapshot
from applications.software_team.management.management_result import TaskItem
from applications.software_team.management.management_result import TaskStatus
from applications.software_team.project.models.project import Project


class ProgressManager:
    """
    统计项目进度：完成率、剩余任务、Agent 工作状态。
    """

    REPORT_DIR = "management"
    REPORT_NAME = "PROGRESS_REPORT.md"

    def __init__(
        self,
        settings: SoftwareTeamSettings | None = None,
    ):

        self._settings = settings or SoftwareTeamSettings()

    def snapshot(
        self,
        project: Project,
        tasks: list[TaskItem],
        *,
        completed_agents: list[str] | None = None,
    ) -> ProgressSnapshot:

        total = len(tasks)
        completed = sum(
            1 for t in tasks if t.status == TaskStatus.COMPLETED
        )
        in_progress = sum(
            1 for t in tasks if t.status == TaskStatus.IN_PROGRESS
        )
        remaining = sum(
            1
            for t in tasks
            if t.status in (TaskStatus.PENDING, TaskStatus.IN_PROGRESS)
        )

        rate = completed / total if total else 0.0

        agent_status = self._build_agent_status(
            tasks,
            completed_agents or [],
        )

        report_path = self._write_report(
            project.workspace_path,
            project,
            tasks,
            rate,
            agent_status,
        )

        return ProgressSnapshot(
            completion_rate=rate,
            total_tasks=total,
            completed_tasks=completed,
            in_progress_tasks=in_progress,
            remaining_tasks=remaining,
            agent_status=agent_status,
            progress_report_path=str(report_path),
        )

    @staticmethod
    def _build_agent_status(
        tasks: list[TaskItem],
        completed_agents: list[str],
    ) -> dict[str, str]:

        status: dict[str, str] = {}

        for task in tasks:

            if task.status == TaskStatus.COMPLETED:

                status[task.assignee] = "completed"

            elif task.status == TaskStatus.IN_PROGRESS:

                status[task.assignee] = "in_progress"

            elif task.status == TaskStatus.BLOCKED:

                status[task.assignee] = "blocked"

            elif task.assignee not in status:

                status[task.assignee] = "pending"

        for agent in completed_agents:

            status.setdefault(agent, "completed")

        return status

    def _write_report(
        self,
        workspace: str | Path,
        project: Project,
        tasks: list[TaskItem],
        rate: float,
        agent_status: dict[str, str],
    ) -> Path:

        workspace_path = Path(workspace)
        report_dir = workspace_path / self.REPORT_DIR
        report_dir.mkdir(parents=True, exist_ok=True)

        report_path = report_dir / self.REPORT_NAME

        task_lines = "\n".join(
            f"| {t.title} | {t.assignee} | {t.status.value} |"
            for t in tasks
        )

        agent_lines = "\n".join(
            f"| {agent} | {state} |"
            for agent, state in sorted(agent_status.items())
        )

        content = f"""# Progress Report — {project.name}

## Completion Rate
{rate:.0%}

## Tasks
| Task | Agent | Status |
|------|-------|--------|
{task_lines}

## Agent Status
| Agent | Status |
|-------|--------|
{agent_lines}

---
*Generated by ProgressManager*
"""

        report_path.write_text(content, encoding=DEFAULT_ENCODING)

        return report_path
