from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class BackendAgent(BaseTeamAgent):
    """
    后端 Agent（P5 智能版）：生成可运行 FastAPI 项目 skeleton。
    """

    DIRECTORY = "backend"

    @property
    def agent_name(self) -> str:
        return "BackendAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        self._verify_dependencies()

        result = self._run_intelligent_loop(context)

        if not result.success:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact = self._finalize_directory_artifact(
            directory_name=self.DIRECTORY,
            metadata={"stage": "developing", "stack": "python"},
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="Backend 生成失败：backend/ 目录为空。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=(
                f"Backend 代码已保存至 {artifact.path}\n\n"
                f"{result.content[:500]}"
            ),
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        architecture = self._get_dependency_content("Architecture.md")

        files = self._generate_backend_files_template(
            context,
            architecture,
        )

        artifact = self._save_directory_artifact(
            directory_name=self.DIRECTORY,
            files=files,
            metadata={
                "stage": "developing",
                "stack": "python",
                "source": "template_fallback",
            },
        )

        return AgentResult(
            success=True,
            model="template_fallback",
            content=f"Backend 已通过模板回退保存至 {artifact.path}",
        )

    def _generate_backend_files_template(
        self,
        context: CoordinatorContext,
        architecture: str,
    ) -> dict[str, str]:

        project = context.project

        main_py = f'''"""
{project.name} - Backend API
Generated by BackendAgent
"""

from fastapi import FastAPI

app = FastAPI(title="{project.name}")


@app.get("/api/health")
def health():
    return {{"status": "ok", "project": "{project.name}"}}


@app.get("/api/items")
def list_items():
    return {{"items": []}}
'''

        return {
            "main.py": main_py,
            "requirements.txt": "fastapi\nuvicorn[standard]\n",
            "README.md": (
                f"# {project.name} Backend\n\n"
                f"Based on architecture:\n\n"
                f"{architecture[:800]}\n"
            ),
        }
