from __future__ import annotations

from pathlib import Path

from applications.software_team.config.defaults import DEFAULT_ENCODING
from applications.software_team.config.settings import SoftwareTeamSettings
from applications.software_team.operations.operation_history import Alert
from applications.software_team.operations.operation_history import Incident
from applications.software_team.operations.operation_history import IncidentResult
from applications.software_team.operations.operation_history import IncidentStatus
from applications.software_team.operations.operation_history import MonitorResult


class IncidentManager:
    """
    记录与管理故障事件（Incident）。

    包括发生时间、影响范围、日志、处理状态。
    """

    REPORT_DIR = "operations"
    REPORT_NAME = "INCIDENT_REPORT.md"

    def __init__(
        self,
        settings: SoftwareTeamSettings | None = None,
    ):

        self._settings = settings or SoftwareTeamSettings()

    def create_from_alerts(
        self,
        workspace: str | Path,
        *,
        alerts: list[Alert],
        monitor: MonitorResult | None = None,
    ) -> IncidentResult:

        if not alerts:

            return IncidentResult(
                success=True,
                incident=None,
            )

        workspace_path = Path(workspace).resolve()
        impact = self._build_impact(alerts)
        logs = self._collect_logs(workspace_path, monitor)

        incident = Incident.create(
            title=self._build_title(alerts),
            impact=impact,
            logs=logs,
            alerts=alerts,
            status=IncidentStatus.OPEN,
            metadata={
                "alert_count": len(alerts),
                "workspace": str(workspace_path),
            },
        )

        report_path = self._write_report(workspace_path, incident, monitor)

        return IncidentResult(
            success=True,
            incident=incident,
            report_path=str(report_path),
        )

    def update_status(
        self,
        incident: Incident,
        status: IncidentStatus,
    ) -> Incident:

        incident.status = status
        incident.metadata["updated_at"] = incident.occurred_at

        return incident

    @staticmethod
    def _build_title(alerts: list[Alert]) -> str:

        primary = alerts[0]

        return (
            f"[{primary.severity.value.upper()}] "
            f"{primary.alert_type}: {primary.message[:80]}"
        )

    @staticmethod
    def _build_impact(alerts: list[Alert]) -> str:

        critical = sum(
            1 for a in alerts if a.severity.value == "critical"
        )
        warning = sum(
            1 for a in alerts if a.severity.value == "warning"
        )

        types = sorted({a.alert_type for a in alerts})

        return (
            f"Alerts: {len(alerts)} "
            f"(critical={critical}, warning={warning}); "
            f"Types: {', '.join(types)}"
        )

    def _collect_logs(
        self,
        workspace: Path,
        monitor: MonitorResult | None,
    ) -> str:

        lines: list[str] = []

        log_dirs = (
            workspace / "logs",
            workspace / "backend" / "logs",
            workspace / "output",
        )

        for log_dir in log_dirs:

            if not log_dir.is_dir():

                continue

            for log_file in sorted(log_dir.glob("*.log"))[:3]:

                try:

                    content = log_file.read_text(
                        encoding=DEFAULT_ENCODING,
                        errors="replace",
                    )

                    lines.append(
                        f"--- {log_file.name} ---\n{content[-2000:]}"
                    )

                except OSError:

                    continue

        if monitor is not None:

            lines.append(f"--- monitor ---\n{monitor.summary}")

        if not lines:

            return "No log files found in workspace."

        return "\n\n".join(lines)

    def _write_report(
        self,
        workspace: Path,
        incident: Incident,
        monitor: MonitorResult | None,
    ) -> Path:

        report_dir = workspace / self.REPORT_DIR
        report_dir.mkdir(parents=True, exist_ok=True)

        report_path = report_dir / self.REPORT_NAME

        alert_lines = "\n".join(
            f"- [{a.severity.value}] {a.alert_type}: {a.message}"
            for a in incident.alerts
        )

        content = f"""# Incident Report

## ID
{incident.id}

## Title
{incident.title}

## Status
{incident.status.value}

## Occurred At
{incident.occurred_at}

## Impact
{incident.impact}

## Alerts
{alert_lines}

## Monitor Summary
{monitor.summary if monitor else 'n/a'}

## Logs
```
{incident.logs[:4000]}
```

---
*Generated by IncidentManager*
"""

        report_path.write_text(content, encoding=DEFAULT_ENCODING)

        return report_path
