from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class ProductAgent(BaseTeamAgent):
    """
    产品 Agent（P5 智能版）。

    通过 Agent Loop + LLM + write_file Tool 生成 PRD.md。
    LLM 不可用时可选回退模板生成。
    """

    PRD_FILENAME = "PRD.md"
    PRD_RELATIVE_PATH = "docs/PRD.md"

    @property
    def agent_name(self) -> str:
        return "ProductAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        existing = self._recover_existing_file_artifact(
            relative_path=self.PRD_RELATIVE_PATH,
            name=self.PRD_FILENAME,
            metadata={
                "format": "markdown",
                "stage": "planning",
            },
            min_chars=400,
        )

        if existing is not None:

            return existing

        result = self._run_intelligent_loop(context)

        if not result.success:

            recovered = self._recover_existing_file_artifact(
                relative_path=self.PRD_RELATIVE_PATH,
                name=self.PRD_FILENAME,
                metadata={
                    "format": "markdown",
                    "stage": "planning",
                },
            )

            if recovered is not None:

                return recovered

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact, content = self._finalize_file_artifact(
            result=result,
            relative_path=self.PRD_RELATIVE_PATH,
            name=self.PRD_FILENAME,
            metadata={
                "format": "markdown",
                "stage": "planning",
            },
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="PRD 生成失败：未产生有效文件内容。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=(
                f"PRD 已生成并保存至 {artifact.path}\n\n"
                f"{content[:500]}"
            ),
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        prd_content = self._generate_prd_template(context)

        artifact = self._create_artifact(
            name=self.PRD_FILENAME,
            artifact_type="document",
            relative_path=self.PRD_RELATIVE_PATH,
            metadata={
                "format": "markdown",
                "stage": "planning",
                "source": "template_fallback",
            },
        )

        self._save_artifact(
            artifact=artifact,
            content=prd_content,
        )

        return AgentResult(
            success=True,
            model="template_fallback",
            content=(
                f"PRD 已通过模板回退生成并保存至 {artifact.path}\n\n"
                f"{prd_content[:500]}"
            ),
        )

    def _generate_prd_template(
        self,
        context: CoordinatorContext,
    ) -> str:

        project = context.project
        tech_stack = (
            ", ".join(project.tech_stack)
            if project.tech_stack
            else "待定"
        )

        return f"""# 产品需求文档（PRD）

## 1. 项目概述

- **项目名称**：{project.name}
- **项目描述**：{project.description or project.requirement}
- **原始需求**：{project.requirement}

## 2. 目标用户

- 系统管理员
- 普通业务用户

## 3. 核心功能

### 3.1 基础功能

1. 用户登录与权限管理
2. 核心业务数据的增删改查
3. 操作日志与审计

### 3.2 扩展功能

1. 数据统计与报表
2. 导入导出
3. 系统配置

## 4. 非功能需求

- **性能**：常规操作响应时间 < 2s
- **可用性**：支持 7×24 小时运行
- **安全**：身份认证、权限控制、数据备份

## 5. 技术栈建议

- {tech_stack}

## 6. 里程碑

| 阶段 | 交付物 |
|------|--------|
| 产品分析 | PRD.md |
| 架构设计 | Architecture.md |
| 后端开发 | Backend API |
| 前端开发 | Frontend UI |
| 测试 | Test Report |
| 文档 | README / API Docs |

## 7. 验收标准

1. 核心功能可正常使用
2. 主要业务流程可跑通
3. 提供可部署说明文档

---
*Generated by ProductAgent*
"""
