from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class ArchitectAgent(BaseTeamAgent):
    """
    架构 Agent（P5 智能版）：基于 PRD 生成 Architecture.md。
    """

    ARCH_FILENAME = "Architecture.md"
    ARCH_RELATIVE_PATH = "docs/Architecture.md"

    @property
    def agent_name(self) -> str:
        return "ArchitectAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        self._verify_dependencies()

        result = self._run_intelligent_loop(context)

        if not result.success:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact, content = self._finalize_file_artifact(
            result=result,
            relative_path=self.ARCH_RELATIVE_PATH,
            name=self.ARCH_FILENAME,
            metadata={
                "format": "markdown",
                "stage": "designing",
            },
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="Architecture 生成失败：未产生有效文件内容。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=f"Architecture 已保存至 {artifact.path}\n\n{content[:500]}",
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        prd = self._get_dependency_content("PRD.md")
        content = self._generate_architecture_template(context, prd)

        artifact = self._create_artifact(
            name=self.ARCH_FILENAME,
            artifact_type="document",
            relative_path=self.ARCH_RELATIVE_PATH,
            metadata={
                "format": "markdown",
                "stage": "designing",
                "source": "template_fallback",
            },
        )

        self._save_artifact(artifact, content)

        return AgentResult(
            success=True,
            model="template_fallback",
            content=f"Architecture 已通过模板回退保存至 {artifact.path}",
        )

    def _generate_architecture_template(
        self,
        context: CoordinatorContext,
        prd: str,
    ) -> str:

        project = context.project

        return f"""# 系统架构文档

## 1. 概述

- **项目**：{project.name}
- **需求摘要**：{project.requirement[:200]}

## 2. 架构风格

- 前后端分离
- RESTful API
- 分层架构：Controller → Service → Repository

## 3. 技术栈

{chr(10).join(f"- {item}" for item in project.tech_stack) or "- Python / FastAPI"}

## 4. 模块划分

| 模块 | 说明 |
|------|------|
| backend | API 服务、业务逻辑、数据访问 |
| frontend | Web 界面 |
| database | 数据模型与迁移 |
| tests | 单元测试与集成测试 |

## 5. 核心 API（草案）

- `GET /api/health` — 健康检查
- `GET /api/items` — 列表查询
- `POST /api/items` — 创建资源
- `PUT /api/items/{{id}}` — 更新资源
- `DELETE /api/items/{{id}}` — 删除资源

## 6. 数据模型（草案）

- User — 用户
- Item — 核心业务实体

## 7. 参考 PRD 摘要

{prd[:1500]}

---
*Generated by ArchitectAgent*
"""
