"""
Library P0 Run13 - Backend API
Generated by BackendAgent
"""

from __future__ import annotations

import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse

# Routers use flat imports (database, repositories, …) relative to backend/
_backend_dir = Path(__file__).resolve().parent
if str(_backend_dir) not in sys.path:
    sys.path.insert(0, str(_backend_dir))

from database import init_db  # noqa: E402
from routers.book_router import router as book_router  # noqa: E402
from routers.borrowing_router import router as borrowing_router  # noqa: E402
from routers.reader_router import router as reader_router  # noqa: E402
from routers.stats_router import router as stats_router  # noqa: E402


@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    yield


app = FastAPI(title="Library P0 Run13", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(book_router)
app.include_router(reader_router)
app.include_router(borrowing_router)
app.include_router(stats_router)


@app.get("/")
def root():
    return RedirectResponse(url="/docs")


@app.get("/api/health")
def health():
    return {"status": "ok", "project": "Library P0 Run13"}


@app.get("/api/items")
def list_items():
    return {"items": []}
