from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class QAAgent(BaseTeamAgent):
    """
    QA Agent（P5 智能版）：基于 backend/ 与 frontend/ 生成 tests/。
    """

    DIRECTORY = "tests"

    @property
    def agent_name(self) -> str:
        return "QAAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        self._verify_dependencies()

        result = self._run_intelligent_loop(context)

        if not result.success:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact = self._finalize_directory_artifact(
            directory_name=self.DIRECTORY,
            metadata={"stage": "testing"},
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="测试代码生成失败：tests/ 目录为空。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=(
                f"测试代码已保存至 {artifact.path}\n\n"
                f"{result.content[:500]}"
            ),
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        backend_summary = self._get_dependency_content("backend")
        frontend_summary = self._get_dependency_content("frontend")

        files = self._generate_test_files_template(
            context,
            backend_summary,
            frontend_summary,
        )

        artifact = self._save_directory_artifact(
            directory_name=self.DIRECTORY,
            files=files,
            metadata={
                "stage": "testing",
                "source": "template_fallback",
            },
        )

        return AgentResult(
            success=True,
            model="template_fallback",
            content=f"测试已通过模板回退保存至 {artifact.path}",
        )

    def _generate_test_files_template(
        self,
        context: CoordinatorContext,
        backend_summary: str,
        frontend_summary: str,
    ) -> dict[str, str]:

        project = context.project

        test_main = f'''"""
{project.name} - Tests
Generated by QAAgent
"""

def test_health_placeholder():
    assert True


def test_items_placeholder():
    items = []
    assert isinstance(items, list)
'''

        test_report = f"""# 测试报告（草案）

## 项目
{project.name}

## 后端覆盖摘要
{backend_summary[:1000]}

## 前端覆盖摘要
{frontend_summary[:1000]}

## 结论
- 基础测试用例已生成
- 待接入 CI 执行
"""

        return {
            "test_main.py": test_main,
            "TEST_REPORT.md": test_report,
        }
