from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class DocumentationAgent(BaseTeamAgent):
    """
    文档 Agent（P5 智能版）：汇总全部 Artifact，生成 README.md。
    """

    README_NAME = "README.md"
    README_RELATIVE_PATH = "README.md"

    @property
    def agent_name(self) -> str:
        return "DocumentationAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        self._verify_dependencies()

        result = self._run_intelligent_loop(context)

        if not result.success:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact, content = self._finalize_file_artifact(
            result=result,
            relative_path=self.README_RELATIVE_PATH,
            name=self.README_NAME,
            metadata={
                "stage": "delivering",
                "format": "markdown",
            },
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="README 生成失败：未产生有效文件内容。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=(
                f"README 已保存至 {artifact.path}\n\n"
                f"{content[:500]}"
            ),
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        all_artifacts = self._artifact_manager.list()
        content = self._generate_readme_template(
            context,
            all_artifacts,
        )

        artifact = self._create_artifact(
            name=self.README_NAME,
            artifact_type="document",
            relative_path=self.README_RELATIVE_PATH,
            metadata={
                "stage": "delivering",
                "format": "markdown",
                "source": "template_fallback",
            },
        )

        self._save_artifact(artifact, content)

        return AgentResult(
            success=True,
            model="template_fallback",
            content=f"README 已通过模板回退保存至 {artifact.path}",
        )

    def _generate_readme_template(
        self,
        context: CoordinatorContext,
        artifacts,
    ) -> str:

        project = context.project

        artifact_lines = "\n".join(
            f"- **{a.name}** ({a.type}) — `{a.path}` by {a.owner}"
            for a in artifacts
        )

        return f"""# {project.name}

## 项目简介

{project.description or project.requirement}

## 需求

{project.requirement}

## 技术栈

{chr(10).join(f"- {t}" for t in project.tech_stack) or "- 见 docs/Architecture.md"}

## 目录结构

```
backend/     # 后端 API
frontend/    # 前端界面
docs/        # PRD 与架构文档
tests/       # 测试
```

## 产物清单

{artifact_lines}

## 快速开始

```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```

## 文档

- [PRD](docs/PRD.md)
- [Architecture](docs/Architecture.md)

---
*Generated by DocumentationAgent*
"""
