from __future__ import annotations

from app.agents.types import AgentResult

from applications.software_team.agents.base.base_team_agent import BaseTeamAgent
from applications.software_team.agents.base.coordinator_context import (
    CoordinatorContext,
)


class FrontendAgent(BaseTeamAgent):
    """
    前端 Agent（P5 智能版）：生成可运行前端项目 skeleton。
    """

    DIRECTORY = "frontend"

    @property
    def agent_name(self) -> str:
        return "FrontendAgent"

    def execute_team(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        self._verify_dependencies()

        result = self._run_intelligent_loop(context)

        if not result.success:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return result

        artifact = self._finalize_directory_artifact(
            directory_name=self.DIRECTORY,
            metadata={"stage": "developing"},
        )

        if artifact is None:

            if self._runtime.settings.enable_template_fallback:

                return self._execute_template_fallback(context)

            return AgentResult(
                success=False,
                model=result.model,
                content="Frontend 生成失败：frontend/ 目录为空。",
            )

        return AgentResult(
            success=True,
            model=result.model,
            content=(
                f"Frontend 代码已保存至 {artifact.path}\n\n"
                f"{result.content[:500]}"
            ),
        )

    def _execute_template_fallback(
        self,
        context: CoordinatorContext,
    ) -> AgentResult:

        architecture = self._get_dependency_content("Architecture.md")

        files = self._generate_frontend_files_template(
            context,
            architecture,
        )

        artifact = self._save_directory_artifact(
            directory_name=self.DIRECTORY,
            files=files,
            metadata={
                "stage": "developing",
                "source": "template_fallback",
            },
        )

        return AgentResult(
            success=True,
            model="template_fallback",
            content=f"Frontend 已通过模板回退保存至 {artifact.path}",
        )

    def _generate_frontend_files_template(
        self,
        context: CoordinatorContext,
        architecture: str,
    ) -> dict[str, str]:

        project = context.project

        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <title>{project.name}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <h1>{project.name}</h1>
  <p>Frontend generated by FrontendAgent</p>
  <button id="loadBtn">加载数据</button>
  <pre id="output"></pre>
  <script src="app.js"></script>
</body>
</html>
"""

        js = """document.getElementById('loadBtn').addEventListener('click', async () => {
  const res = await fetch('/api/items');
  const data = await res.json();
  document.getElementById('output').textContent = JSON.stringify(data, null, 2);
});
"""

        css = "body { font-family: sans-serif; margin: 2rem; }\n"

        return {
            "index.html": html,
            "app.js": js,
            "styles.css": css,
            "README.md": (
                f"# {project.name} Frontend\n\n"
                f"{architecture[:600]}\n"
            ),
        }
